### ISSUE TITLE
Unable to find a specification for `BeaconClientDApp`

### ISSUE THREAD

**Issue by bibash28** [airgap-it/beacon-ios-sdk#20]
.podspec file
```
  s.dependency 'BeaconBlockchainSubstrate'
  s.dependency 'BeaconBlockchainTezos'
  s.dependency 'BeaconClientWallet'
  s.dependency 'BeaconCore'
  s.dependency 'BeaconTransportP2PMatrix'
  s.dependency 'BeaconClientDApp'
  s.platform = :ios, '13.0'
```

Error
```
[!] Unable to find a specification for `BeaconClientDApp` depended upon by `beacon`

You have either:
 * out-of-date source repos which you can update with `pod repo update` or with `pod install --repo-update`.
 * mistyped the name or version.
 * not added the source repo that hosts the Podspec to your Podfile.
```

**Comment by jsamol** [comment]
`BeaconClientDApp` is a new package, please make sure that you use the latest SDK version (as for now it's `v3.2.1`). Also, please note that Beacon SDK hasn't been published to the Specs repo and the only way of getting it is through GitHub, as described in [the README](https://github.com/airgap-it/beacon-ios-sdk#cocoapods).

**Comment by jsamol** [comment]
Recently I've learnt that there's [a project](https://github.com/EjaraApp/beacondart) whose developers needed the pods published and they published them. The pods you are trying to pull are most probably coming from them. Since it's outside of our control, I'm closing the issue. You should reach out to the team that maintains the publication if you stumble upon any issues.

**Comment by jayluxferro** [comment]
@bibash28 , the pod update has been made. (see attached image)

<img width="1356" alt="Screen Shot 2022-09-13 at 8 23 03 AM" src="https://user-images.githubusercontent.com/8394019/189850497-261d2a17-b646-45f1-80fc-efb47a8996fc.png">

**Comment by bibash28** [comment]
Thanks a lot..
