### ISSUE TITLE
getPeers returns all list with false flag

### ISSUE THREAD

**Issue by bibash28** [airgap-it/beacon-ios-sdk#22]
private var beaconClient: Beacon.WalletClient? = nil
beaconClient?.getPeers called

**Comment by jsamol** [comment]
Thanks for the report, it was fixed in `v3.2.3`.

Next time, when you're opening an issue, please try to elaborate a little more on the problem. I know that we'd talked on Slack about this bug and you explained it there, but in general an issue should be self-contained and not require any additional context to understand what it is about. Not only would it help me or any other developer trying to fix the bug jump on the issue easier, but also other people, who may have experienced a similar problem, could see that the bug was found and worked on already.

I've added issue templates. From now on, every issue must follow one of the templates, otherwise it'll be immediately closed.

If you still have problems with peers being incorrectly flagged, please, open a new issue using the `Bug Report` template 🙂
